### ISSUE TITLE
MissingParentRecordsReport - external ids 

### ISSUE THREAD

**Issue by gidglass** [hknokh/SFDMU-Wiki#1]
It seems like the external id isn't being respected since its being logged as the Name field in the csv as opposed to the composite one specified in the export json? Please see below:

export.json:
```
{
    "objects": [
        {
            "query": "SELECT Id, readonly_false FROM Targeting_Category__c",
            "operation": "Upsert",
            "externalId": "Category__r.Name__c;Name__c;JSONName__c;Date_Label_1__c;Date_Label_2__c;Number_Label_1__c;Number_Label_2__c;Picklist_Label_1__c;Picklist_Label_2__c;Text_Label_1__c"
        },
        {
            "query": "SELECT Id, readonly_false FROM Hierarchy__c",
            "operation": "Upsert",
            "externalId": "Code__c;GUID__c"
        }
    ]
}
```

MissingParentRecordsReport:
```
Date update,Id,Child ExternalId,Child lookup,Child SObject,Missing value,Parent ExternalId,Parent SObject
2020-05-19  16:08:06.332,a0Nc00000085w0nEAA,Targeting_Hierarchy__r.Name,Targeting_Hierarchy__c,Targeting_Category__c,H-17027,Name,Hierarchy__c
2020-05-19  16:08:06.334,a0Nc00000085vyNEAQ,Targeting_Hierarchy__r.Name,Targeting_Hierarchy__c,Targeting_Category__c,H-17027,Name,Hierarchy__c
2020-05-19  16:08:06.334,a0Nc00000085vyQEAQ,Targeting_Hierarchy__r.Name,Targeting_Hierarchy__c,Targeting_Category__c,H-17027,Name,Hierarchy__c
2020-05-19  16:08:06.334,a0Nc00000085vyiEAA,Targeting_Hierarchy__r.Name,Targeting_Hierarchy__c,Targeting_Category__c,H-33314,Name,Hierarchy__c
2020-05-19  16:08:06.334,a0Nc00000085vyjEAA,Targeting_Hierarchy__r.Name,Targeting_Hierarchy__c,Targeting_Category__c,H-23000,Name,Hierarchy__c
```

All self-referencing records are inserted correctly, but the relationship between these two objects are not being populated.

**Comment by hknokh** [comment]
Hello @gidglass 
I tried your scenario in both sobjects selecting fields with readonly_false + in both objects are composite external ids + objects are related. Can't reproduce the issue.
I think you have outdated versin. Check your version with:
 **sfdx sfdmu:run --version**  
The response should be:
**Plugin version: sfdmu v2.8.323**
If the version number is earlear you need to perform:
**sfdx plugins:uninstall sfdmu
sfdx plugins:install sfdmu**
then ensure you have the latest version:
 **sfdx sfdmu:run --version**

**Comment by gidglass** [comment]
@hknokh - thanks for your help. I verified that I do have the latest version installed (v2.8.323) but still the problem persists. Odd :(

Here's the basic data model as an fyi:

**Object_1__c** (Hierarchy__c in the above exports.json)
- Has optional self-referencing lookup to itself
- Uses a composite external id composed of multiple fields on Object_1__c

**Object_2__c** (Targeting_Category__c in the above exports.json)
- Has optional self-referencing lookup to itself
- Had optional lookup to Object_1__c
- Uses a composite external id composed of multiple fields on Object_1__c and Object_2__c

**Comment by hknokh** [comment]
Hi @gidglass this is something weird with this issue, let me check much deeper and it could take a time. I will keep you updated.

**Comment by hknokh** [comment]
@gidglass 
Can I ask you to duplicate your issue on the main project tracker:
https://github.com/forcedotcom/SFDX-Data-Move-Utility/issues   ?

I just wanted to concentrate all the issues in one place and then to block this tracker of WIKI, unfortunatelly I can't move this issue to there myself, cause I'm not the owner of the main repo.

Thanks!
